"""Deterministic diagrams and tables for generated documentation (Task 24).

Rendered directly from collected evidence (docgen/collector.py) rather than generated by
Claude, so resource names and relationships in the diagrams/table can never be hallucinated -
only what's actually in the evidence appears. Output is Mermaid syntax (renders natively in
GitLab/GitHub Markdown and in most Markdown viewers) plus a plain Markdown table.
"""
import re
from typing import Any, Dict, List, Optional

_MAX_DIAGRAM_ITEMS = 10


def _node_id(label: str, prefix: str = "n") -> str:
    slug = re.sub(r"[^a-zA-Z0-9]", "_", label or "unknown").strip("_") or "unknown"
    return f"{prefix}_{slug}"[:60]


def _friendly_type(resource_type: str) -> str:
    label = (resource_type or "").split("/")[-1]
    return label.replace("managedclusters", "AKS Cluster").replace("sites", "App Service").replace(
        "serverfarms", "App Service Plan"
    ).replace("registries", "Container Registry").replace("vaults", "Key Vault").replace(
        "storageaccounts", "Storage Account"
    ).replace("servers", "SQL Server").replace("redis", "Redis").replace(
        "components", "Application Insights"
    ).replace("workspaces", "Log Analytics") or label or "Resource"


def build_dependency_diagram(
    project_name: str,
    azure_resources: List[Dict[str, Any]],
    aks_cluster: Optional[Dict[str, Any]] = None,
    aks_namespace: Optional[str] = None,
    aks_deployments: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """Mermaid flowchart of the project's infrastructure dependency graph."""
    lines = ["```mermaid", "flowchart TD"]
    project_node = _node_id(project_name, "gl")
    lines.append(f'    {project_node}["🦊 {project_name} (GitLab)"]')

    if not azure_resources:
        lines.append(f'    {project_node} -.->|no Azure resources correlated| none["(none found)"]')
        lines.append("```")
        return "\n".join(lines)

    for resource in azure_resources[:_MAX_DIAGRAM_ITEMS]:
        name = resource.get("name") or "unknown"
        node = _node_id(name, "az")
        label = f"{_friendly_type(resource.get('type', ''))}\\n{name}"
        lines.append(f'    {node}["{label}"]')
        lines.append(f"    {project_node} --> {node}")

    if len(azure_resources) > _MAX_DIAGRAM_ITEMS:
        lines.append(f'    more["+{len(azure_resources) - _MAX_DIAGRAM_ITEMS} more resources"]')
        lines.append(f"    {project_node} --> more")

    if aks_cluster:
        cluster_node = _node_id(aks_cluster.get("name") or "aks", "az")
        if aks_namespace:
            ns_node = _node_id(aks_namespace, "ns")
            lines.append(f'    {ns_node}["Namespace: {aks_namespace}"]')
            lines.append(f"    {cluster_node} --> {ns_node}")
            parent = ns_node
        else:
            parent = cluster_node
        for deployment in (aks_deployments or [])[:_MAX_DIAGRAM_ITEMS]:
            dep_name = deployment.get("name") or "deployment"
            dep_node = _node_id(dep_name, "dep")
            lines.append(f'    {dep_node}["Deployment: {dep_name}"]')
            lines.append(f"    {parent} --> {dep_node}")

    lines.append("```")
    return "\n".join(lines)


def build_deployment_flow_diagram(
    default_branch: Optional[str],
    latest_pipeline: Optional[Dict[str, Any]],
    stages: List[Dict[str, Any]],
    environments: List[Dict[str, Any]],
    target_label: Optional[str],
) -> str:
    """Mermaid flowchart of the CI/CD deployment flow: commit -> pipeline stages -> environment(s) -> target."""
    lines = ["```mermaid", "flowchart LR"]
    commit_node = "commit"
    branch_label = default_branch or "default branch"
    lines.append(f'    {commit_node}(["Commit to {branch_label}"])')

    previous = commit_node
    if not stages:
        lines.append('    nopipeline["No pipeline stages found"]')
        lines.append(f"    {previous} --> nopipeline")
    else:
        for stage in stages[:_MAX_DIAGRAM_ITEMS]:
            stage_name = stage.get("name") or "stage"
            node = _node_id(stage_name, "st")
            status = stage.get("status", "")
            lines.append(f'    {node}["{stage_name} ({status})"]')
            lines.append(f"    {previous} --> {node}")
            previous = node

    if environments:
        for env in environments[:_MAX_DIAGRAM_ITEMS]:
            env_name = env.get("name") or "environment"
            node = _node_id(env_name, "env")
            lines.append(f'    {node}(["Environment: {env_name}"])')
            lines.append(f"    {previous} --> {node}")
        previous = _node_id(environments[0].get("name") or "environment", "env")

    if target_label:
        target_node = _node_id(target_label, "target")
        lines.append(f'    {target_node}["{target_label}"]')
        lines.append(f"    {previous} --> {target_node}")

    lines.append("```")
    return "\n".join(lines)


_INVENTORY_HEADER = ["Name", "Type", "Resource Group", "Region", "Managed Identity", "Monthly Cost"]


def build_resource_inventory_rows(
    azure_resources: List[Dict[str, Any]], cost_breakdown: Optional[List[Dict[str, Any]]] = None
) -> List[List[str]]:
    """[header, *rows] table data for every correlated Azure resource - the single source of
    truth both the Markdown table and the DOCX/PDF native tables are built from."""
    # Keyed by full Resource ID, never by name - resource names aren't unique (e.g. two
    # different "optimusx-backend-plan" App Service Plans exist in different resource groups on
    # this subscription), so a name-keyed lookup can silently attach one resource's cost to a
    # different resource in the generated inventory table.
    cost_by_id = {
        item.get("resource_id", "").lower(): item for item in (cost_breakdown or []) if item.get("resource_id")
    }
    rows = [_INVENTORY_HEADER]
    for resource in azure_resources:
        name = resource.get("name") or "Unknown"
        identity = (resource.get("_identity") or {}).get("type") or "None"
        resource_id = (resource.get("id") or resource.get("resource_id") or "").lower()
        cost_entry = cost_by_id.get(resource_id)
        cost_text = (
            f"${cost_entry['monthly_cost']:,.2f} {cost_entry.get('currency', '')}".strip()
            if cost_entry and cost_entry.get("monthly_cost") is not None
            else "Unknown"
        )
        rows.append([
            name,
            _friendly_type(resource.get("type", "")),
            resource.get("resource_group", "Unknown"),
            resource.get("region", "Unknown"),
            identity,
            cost_text,
        ])
    return rows


def build_resource_inventory_table(
    azure_resources: List[Dict[str, Any]], cost_breakdown: Optional[List[Dict[str, Any]]] = None
) -> str:
    """Markdown table of every correlated Azure resource: name, type, resource group, region,
    managed identity, and monthly cost (when known)."""
    if not azure_resources:
        return "_No Azure resources were automatically correlated with this project._"

    rows = build_resource_inventory_rows(azure_resources, cost_breakdown)
    header, data_rows = rows[0], rows[1:]
    lines = [f"| {' | '.join(header)} |", "|" + "---|" * len(header)]
    for row in data_rows:
        lines.append(f"| {' | '.join(str(cell) for cell in row)} |")
    return "\n".join(lines)
